---
- hosts: all
  tasks:
  - name: Ansible create file with content example
    copy:
      dest: "/usr/share/tomcat/conf/Catalina/localhost/manager.xml"
      content: |
        <Context privileged="true" antiResourceLocking="false" docBase="${catalina.home}/webapps/manager">   
            <Valve className="org.apache.catalina.valves.RemoteAddrValve" allow="^.*$" />
        </Context>
