---
- hosts: all
  tasks:
  - name: delete old manager
    lineinfile:
      path: /usr/share/tomcat/conf/tomcat-users.xml
      state: absent
      regexp: '^<user username="admin" password="admin" roles="manager-gui,admin-gui" />' 

  
