---
- hosts: all

  vars:
    mariadb_root_password: "testpassword1"
    mariadb_database: "youtube"

  tasks:
  # Servidor Base de daros
  - name: Tomcat deployment playbook
  	become: yes               # If to escalate privilege
  	become_method: sudo       # Set become method
  	remote_user: root         # Update username for remote server
  	vars:
    	tomcat_ver: 9.0.30                          # Tomcat version to install
    	ui_manager_user: manager                    # User who can access the UI manager section only
        ui_manager_pass: manager
    	ui_admin_username: admin                    # User who can access bpth manager and admin UI sections
    	ui_admin_pass: admin          # UI admin password
  	roles:
    	- tomcat

  - name: Download Java JRE
	get_url:
	url: http://download.oracle.com/otn-pub/java/jdk/8u60-b27/jre-8u60-linux-x64.rpm
	dest: /opt/jre-8u60-linux-x64.rpm
	headers: 'Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie'

  - name: install Java JRE rpm from a local file
	yum:
	name: /opt/jre-8u60-linux-x64.rpmstate: present

  - name: Download Java JDK
	get_url:
	url: http://download.oracle.com/otn-pub/java/jdk/8u60-b27/jdk-8u60-linux-x64.rpm
	dest: /opt/jdk-8u60-linux-x64.rpm
	headers: 'Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie'

  - name: Install Java JDK rpm from a local file
	yum:
	name: /opt/jdk-8u60-linux-x64.rpm
	state: present

  - name: install the latest version of Apache Maven
 	yum:
	name: maven
	state: latest
        

