---
- hosts: all
  tasks:
  - name: insertar rol manage-script
    lineinfile: 
      path: /usr/share/tomcat/conf/tomcat-users.xml
      backup: yes
      insertafter: '^<role rolename="manager-gui" />'
      line: '<role rolename="manager-script" />'
 
